title: RS/LLM Arxiv Daily
description: Automatically Update RS/LLM Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true

github:
  zip_url: https://github.com/ler0n/rs_llm-arxiv-daily
  another_url: https://github.com/ler0n/rs_llm-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  # twitter: AlphaRealcat
  github: ler0n

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
